### ISSUE TITLE
not accumulating passes with successful solved captchas

### ISSUE THREAD

**Issue by 4evermaat** [privacypass/challenge-bypass-extension#145] opened 2019-11-28 16:32 UTC
I solved several captchas from https://captcha.website/ and I'm not getting any captchas saved into my browsers.

Chrome `78.0.3904.97 x64 bit`  (edit:  and just now `78.0.3904.108  x64 bit` 
PrivacyPass 2.0.3

Firefox `68.2.0esr (64-bit)`
PrivacyPass 2.0.3

But all I see are 3 `!!!` on the browser extension icon.   No accumulated passes.    

Am I doing something wrong?

I already checked #32 #97 #25 #30 #90 

I don't understand why the passes are not saving.  Is there any log that can be presented here to prove/disprove my usage of the product?

**Comment by alxdavids** [comment] 2019-11-28 16:37
This is a duplicate of #141, apologies the issue was accidentally closed. A fix has been merged but we still need to release a new version of the extension to the Chrome and FF stores.

**Closed** 2019-11-28 16:49 UTC
Labels: duplicate
