### ISSUE TITLE
When I finish hcaptcha, the privacy pass does not get the corresponding tokens

### ISSUE THREAD

**Issue by yuijker** [privacypass/challenge-bypass-extension#296] opened 2022-02-08 05:25 UTC
operating system： windows 10
Web browser :edge 98.0.1108.43
Extension version：3.0.1
Problem description：
When I finish hcaptcha, privacy pass extension should give corresponding tokens， At least five of then，
But for some unknown reason, the extension does not give any tokens at all. Here are some screenshots：

![屏幕截图 2022-02-08 132344](https://user-images.githubusercontent.com/72558803/152923645-cc6bf4f6-b064-4b2f-a7f7-65ec6ea027bd.png)

![屏幕截图 2022-02-08 132441](https://user-images.githubusercontent.com/72558803/152923653-97fdb968-2394-47a1-b623-702b1c383b98.png)

**Comment by munkiepus** [comment] 2022-02-08 10:20
this is a duplicate of https://github.com/privacypass/challenge-bypass-extension/issues/247

**Closed** 2022-02-19 03:57 UTC
