### ISSUE TITLE
No passes generated

### ISSUE THREAD

**Issue by nukeop** [privacypass/challenge-bypass-extension#90] opened 2019-03-27 08:48 UTC
I am forced to use this by cloudflare which presents me with a captcha wherever I go that has to be solved upwards of 10 times each time I want to refresh a page that goes through them.

Solving it on cloudflare's warning website doesn't generate any free passes, and captcha.website doesn't contain any captcha for me to solve either.

**Comment by alxdavids** [comment] 2019-03-28 10:47
This sounds like a duplicate of #25 so I'm going to close this. If you have any information that differs from the discussion in there can you provide your replication steps and browser configuration, thanks!

**Closed by alxdavids** 2019-03-28 10:47 UTC
