### ISSUE TITLE
When I finish Cloudflare challenge, the captcha.wetsite show me the Privacy Pass homepage and get no tokens 

### ISSUE THREAD

**Issue by zanderpeng** [privacypass/challenge-bypass-extension#306] opened 2022-02-18 08:05 UTC
operating system： windows 2019
Web browser :chrome 98.0.4758.102
Extension version：3.0.1
Problem description：
When I finish Cloudflare challenge, the captcha.wetsite show me the Privacy Pass homepage and get no tokens 
![2022-02-18 160256](https://user-images.githubusercontent.com/51562178/154642787-5f14ba59-0246-48e7-879d-f5190b3d91a6.png)

**Comment by warren-bank** [comment] 2022-02-19 07:33
fwiw, I just retested the most recent [release](https://github.com/warren-bank/fork-crx-PrivacyPass-challenge-bypass/releases) of the extension built from PR #283 ..and it still works correctly. This version was built nearly 3 weeks ago, as the PR hasn't received any feedback. Maybe somebody could take a look at its code.. and we could merge some of its many updates?

**Comment by zanderpeng** [comment] 2022-02-19 09:46
I just test version：2.0.7,in this version  hcaptcha is work, I get tokens.But Cloudflare still can't work. 
By the way，which version is work？ where I can find it for chrome

**Comment by tumagonx** [comment] 2022-02-19 17:28
> fwiw, I just retested the most recent [release](https://github.com/warren-bank/fork-crx-PrivacyPass-challenge-bypass/releases) of the extension built from PR #283 ..and it still works correctly (with a few [documented caveats](https://github.com/privacypass/challenge-bypass-extension/pull/283#issuecomment-1025258736) ). This version was built nearly 3 weeks ago, as the PR hasn't received any recent feedback. Maybe somebody could take a look at its code.. and we could merge some of its many updates?

Thanks your fork works!
tested version 3.6.6 on Windows XP, Chrome 78, Tor 0.3.5.10

**Comment by zanderpeng** [comment] 2022-02-20 05:50
> > fwiw, I just retested the most recent [release](https://github.com/warren-bank/fork-crx-PrivacyPass-challenge-bypass/releases) of the extension built from PR #283 ..and it still works correctly (with a few [documented caveats](https://github.com/privacypass/challenge-bypass-extension/pull/283#issuecomment-1025258736) ). This version was built nearly 3 weeks ago, as the PR hasn't received any recent feedback. Maybe somebody could take a look at its code.. and we could merge some of its many updates?


> 
> Thanks your fork works! tested version 3.6.6 on Windows XP, Chrome 78, Tor 0.3.5.10

when I test 3.6.6 on Windwos 2019 , Chrome 98, it show me this 
![test](https://user-images.githubusercontent.com/51562178/154830380-2940e75a-bd52-4d27-b227-1e8345eb6b3f.PNG)

**Comment by warren-bank** [comment] 2022-02-20 05:59
@zanderpeng
* you tried to install a [crx2](https://github.com/warren-bank/fork-crx-PrivacyPass-challenge-bypass/releases/download/v3.6.6/PrivacyPass.crx2.crx)..
  - wrong!
* recent versions of Chrome only support [crx3](https://github.com/warren-bank/fork-crx-PrivacyPass-challenge-bypass/releases/download/v3.6.6/PrivacyPass.crx3.crx)..
  - please try again using the correct format

**Comment by zanderpeng** [comment] 2022-02-20 10:35
actually,I try both of crx2 and crx3. but they have the same question

**Comment by warren-bank** [comment] 2022-02-20 11:19
trying to reproduce..
* decompressed a fresh copy of Google Chrome [98.0.4758.102 portable](https://portableapps.com/apps/internet/google_chrome_portable)
* chrome://extensions
  * `developer mode` = `false`
    - crx3 does not install
    - package is invalid: `CRX_REQUIRED_PROOF_MISSING`
  * `developer mode` = `true`
    - crx3 installs
    - package is permanently disabled because it isn't verified by Google
  * `developer mode` = `true`
    - unpacked crx3 installs
    - package is enabled
    - extension is fully functional

**Comment by tumagonx** [comment] 2022-02-20 11:33
I use crx2, and since Chrome (360 EE) is run as Guest user, all of my extensions are in developer mode.

**Comment by warren-bank** [comment] 2022-02-20 11:41
according to [this Chrome changelog](https://en.wikipedia.org/wiki/Google_Chrome_version_history), version 73.0.3683 is when Chrome ended support for installing crx2 extensions; this and all subsequent versions of Chrome only allow crx3.

**Comment by warren-bank** [comment] 2022-02-20 11:45
I'm back to using SRWare Iron 85 now.. and just tried to install the crx2;<br>it refuses with the error: `CRX_HEADER_INVALID`<br>..which basically just means that it requires a crx3 instead.

**Comment by tumagonx** [comment] 2022-02-20 12:13
oops sorry I have 2 chrome 69 and 78, this one us 69 :D
![Untitled](https://user-images.githubusercontent.com/4075264/154841885-cffeb6d0-b8b3-4c9b-8f8a-ba7ba5123b15.png)

**Comment by warren-bank** [comment] 2022-02-20 12:20
fun fact..

since the crx2 extension is expected to be used in older browsers,<br>which will be using a javascript engine that doesn't support all modern language features;<br>the crx2 extensions that I release:
* are fully converted to ES5
* include the [core-js](https://github.com/zloirock/core-js) polyfill library

**Comment by warren-bank** [comment] 2022-02-20 12:58
another fun fact..

all of the text presented in the extension's UI has been setup for [internationalization](https://github.com/warren-bank/fork-crx-PrivacyPass-challenge-bypass/tree/v3.6.6/public/_locales).

atm, I've only included [english](https://github.com/warren-bank/fork-crx-PrivacyPass-challenge-bypass/blob/v3.6.6/public/_locales/en/messages.json)..<br>but translations will be very easy to add later.

**Comment by tumagonx** [comment] 2022-03-19 21:01
is this happen again? please reopen
I tried like 10 times solving the puzzle, never got cloudflare token, hcaptcha works.

**Comment by warren-bank** [comment] 2022-03-20 00:56
observations:
* yep, I can confirm that the Cloudflare provider has (yet again) made breaking changes
* in Chrome devtools, inspecting the network tab for the background page:
  - the extension is still correctly:
    * detecting and intercepting the correct request
    * sending its own request for Cloudflare to sign tokens
  - the Cloudflare backend is now incorrectly:
    * responding to the extension's request with a 403 status code
      - the content of the response is the HTML page that is seen in the browser,
      - rather than a JSON data structure containing signed tokens

status:
* in the month since this issue was closed:
  - my fork has received no feedback or any attempt to merge any changes
  - aside from adding string translations, I haven't made any farther changes
* I'm not eager to devote much additional effort to my fork, because:
  - this project isn't being actively maintained
  - contributions are largely ignored
  - the captcha providers are constantly making changes without any apparent coordination with this project
    * which makes its foundation very unstable

**Comment by tumagonx** [comment] 2022-03-20 01:57
dang that sounds like legitimate way of cloudflare try kills tor users like me (not a bot!), 
I wonder how other tor users survive this blatant internet censorship considering most website use cloudflare services. And here i am trying to escape government censorship (reddit blocked) only to get toyed by cloudflare.
No way I'll use expensive VPN service though.

**Comment by ppopth** [comment] 2022-03-20 03:10
Yes, we made a change on the backend, but it should have been solved in https://github.com/privacypass/challenge-bypass-extension/pull/308 and it was released with v3.0.2

If you haven't updated the version to v3.0.2, please do so. Then, if the issue still exists, we will investigate on that.

**Comment by warren-bank** [comment] 2022-03-20 03:32
@tumagonx I'll push an update.. I imagine it should be a trivial fix to rejigger the request parameters to compensate for whatever change was recently made on the backend. I'll look at it later tonight.

**Comment by warren-bank** [comment] 2022-03-20 08:16
@tumagonx fwiw, [v3.7.2](https://github.com/warren-bank/fork-crx-PrivacyPass-challenge-bypass/releases/tag/v3.7.2) issues Cloudflare tokens again. A querystring parameter in the request to issue CF tokens was renamed.

**Comment by tumagonx** [comment] 2022-03-20 13:58
@warren-bank you save the day, I'll try learn the changes in case of another breaks happen.

**Comment by aravindvnair99** [comment] 2022-04-03 09:44
The issue continues in version 3.0.2 of the extension as well. I get Cloudflare but not hCaptcha.

![image](https://user-images.githubusercontent.com/22199259/161421317-54a0201d-55da-4d24-8f20-ee4e7d0e9f88.png)

<html>
<body>


Google Chrome | 100.0.4896.60 (Official Build) (64-bit) (cohort: Stable Installs & Version Pins)
-- | --



</body>
</html>
<html>
<body>


OS | Windows 11 Version 21H2 (Build 22000.593)
-- | --



</body>
</html>

# Related / similar open issues:
- #274
- #299
- #310

**Comment by armfazh** [comment] 2022-11-14 21:24
@zanderpeng try the new version [v3.0.4](https://github.com/privacypass/challenge-bypass-extension/tree/v3.0.4), and open a new ticket if you had a new issue.

**Closed by armfazh** 2022-11-14 21:24 UTC

**Comment by Deyrap355** [comment] 2022-11-16 00:44
How can I help and change   HTML  to   JSON data, I have been having too of
trouble
