### ISSUE TITLE
Privacy Pass not working

### ISSUE THREAD

**Issue by Synetos33** [privacypass/challenge-bypass-extension#337] opened 2022-06-23 05:39 UTC
Hello,

When I visit a cloudflare-protected site, the site gets stuck in a redirect loop, drains my captcha credits, and finally times out.

Please fix.

**System (please complete the following information):**
 - OS: Windows10
 - Cloudflare tokens or hCaptcha tokens? hCaptcha
 - Browser Chrome: 
 - Browser Version 102.0.5005.115 (Official Build) (64-bit)
 - Privacy Pass Version Version 3.0.3

**Additional context**
fuck cloudflare. fuck the privacy pass.

**Comment by cbarak** [comment] 2022-06-23 11:13
I have the same problem since June 17th. Win10, Firefox 101.01

**Comment by armfazh** [comment] 2022-06-23 16:33
unable to reproduce bad behaviour on Firefox 101.0.1 & Linux. 
Wondering if this is specific to Windows.

**Comment by armfazh** [comment] 2022-06-23 19:44
@Synetos33 what is website where you observed that behaviour?

**Comment by cbarak** [comment] 2022-06-23 22:58
Here's a site that fails for me:
https://www.artandlife.gr/

**Comment by Synetos33** [comment] 2022-06-24 00:18
Thanks for your reply @armfazh .  I sent you an email with the web site that's problematic for me.

Thanks for your input on this too, @cbarak .

**Comment by Synetos33** [comment] 2022-06-27 13:18
Hello, can this problem be fixed? Please help.

**Comment by robd003** [comment] 2022-07-09 02:46
I'm also seeing this on macOS w/ Brave

**Comment by OneCrazyRussian** [comment] 2022-08-08 06:13
Same thing on latest 103 Firefox, gets stuck in a loop. 
Also "get more passes" site captcha dot website does nothing after completing the hCaptcha

**Comment by ziproot** [comment] 2022-10-04 22:28
Same. [See HAR file](https://upload.disroot.org/r/mVHo1wa9#4dNHTHv++b9uuFQxoqZOIABVBo6+VvLhGDWd3Nx44vU=)

**Comment by migueldemoura** [comment] 2022-10-04 22:41
> Same. [See HAR file](https://upload.disroot.org/r/mVHo1wa9#4dNHTHv++b9uuFQxoqZOIABVBo6+VvLhGDWd3Nx44vU=) EDIT: This was for captcha.website and did not generate passes. I thought it was appropriate to send here.

Hi @ziproot, thanks for providing a .har!
Do you use any extensions or custom config in the Tor Browser (I assume it's that browser since you linked #342)?

**Comment by migueldemoura** [comment] 2022-10-17 15:55
The TOR Browser issue is separate, and we've recently addressed it, see https://github.com/privacypass/challenge-bypass-extension/issues/342.

**Comment by thibmeu** [comment] 2023-12-21 11:26
Closing this issue in favor of #400, where a major reshape is being centralised to support IETF version.

**Closed by thibmeu** 2023-12-21 11:26 UTC
