### ISSUE TITLE
please t

### ISSUE THREAD

**Issue by fisforfaheem** [privacypass/challenge-bypass-extension#248] opened 2021-09-01 13:08 UTC
dear sir, I am having so many issues from last two weeks tried everything no 
![image](https://user-images.githubusercontent.com/35878088/131676721-17debad3-8a27-40eb-85cf-604d5ab2d5db.png)
luck please fix

**Comment by ppopth** [comment] 2021-09-02 14:13
Duplicate of #247

**Closed** 2022-01-17 03:46 UTC
