### ISSUE TITLE
Brave Browser Privacy Pass not work anymore

### ISSUE THREAD

**Issue by usafety** [privacypass/challenge-bypass-extension#226] opened 2021-04-06 19:40 UTC
I use Brave Browser and its notw work anymore

**Comment by AirBashX** [comment] 2021-04-14 08:26
me too,There is no longer role in the Chrome89 version.

**Comment by BTCAlchemist** [comment] 2021-04-29 17:09
Same issue for me. For example, when I go to etherscan.io, it prompts me to complete hCaptcha. When I click Privacy Pass to activate the browser extension and reload the page, then click the hCaptcha check box, I am still required to solve the hCaptcha puzzle. This happens with Brave shields on and off, and I noticed it sometime last year. Solving this could really save users time and make Privacy Pass worthwhile. I am using Brave browser on Windows 10. @alxdavids Can you help?

![image](https://user-images.githubusercontent.com/56145569/116590447-9fa63300-a8d2-11eb-907d-e5b462894252.png)

**Comment by 7ik1t4** [comment] 2021-05-02 13:02
For me, it's working. May be update it
![image](https://user-images.githubusercontent.com/46179582/116814113-ca171b00-ab74-11eb-9c90-7e605ef46716.png)

**Comment by usafety** [comment] 2021-05-04 19:13
Same problem

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by BTCAlchemist** [comment] 2021-05-04 20:48
@armfazh @durch Are you able to help?

**Comment by armfazh** [comment] 2021-05-04 21:39
Using Brave
```
Brave	1.23.75 Chromium: 90.0.4430.93 (Official Build) (64-bit)
Revision	4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS	Linux
```

Go to collect passes by clicking in [PP] -> Cloudflare -> Get More Passes.
This prompts [captcha.website](https://captcha.website) and solve the captcha.
With 30 CF and 5 hCaptcha passes, you can go to a website protected by Cloudflare and spend these passes.
You can verify whether a site is behind Cloudflare using [Claire](https://chrome.google.com/webstore/detail/claire/fgbpcgddpmjmamlibbaobboigaijnmkl)
However note that each website could turn off PrivacyPass at its sole discretion.

**Comment by armfazh** [comment] 2021-05-04 21:41
> BTCAlchemist
> Same issue for me. For example, when I go to etherscan.io, it prompts me to complete hCaptcha. When I click Privacy Pass to activate the browser extension and reload the page, then click the hCaptcha check box, 

you might need to click on [PP] -> Cloudflare -> Get More Passes, or go to [captcha.website](https://captcha.website) directly.

**Comment by BTCAlchemist** [comment] 2021-05-05 19:37
@armfazh Thank you for your reply. I followed your instructions: I had 19 Cloudflare and 4 hCaptcha passes. I went to captcha.website, completed the puzzle, and I now have 49 Cloudflare passes and 4 hCaptcha passes. However, when I try using Privacy Pass in Brave browser (most recent version 1.23.75) at https://www.tokyobitcoiner.com/hcaptcha, the hCaptcha challenge continues to pop up. Does it work for you? How else to troubleshoot this?

Here are my Privacy Pass extension settings:
![image](https://user-images.githubusercontent.com/56145569/117199071-9d464c00-ad9e-11eb-946a-514b7c20d168.png)


> you might need to click on [PP] -> Cloudflare -> Get More Passes, or go to [captcha.website](https://captcha.website) directly.

**Comment by armfazh** [comment] 2021-05-05 22:15
This seems to be an issue with hCaptcha tokens
cc: @durch

**Comment by BTCAlchemist** [comment] 2021-05-10 22:23
No, I had Brave shields disabled.

> maybe Google blocks it :) Or Brave Shield or something.

**Comment by BTCAlchemist** [comment] 2021-06-17 03:25
Following up on this. I am using Craigslist and frustrated, losing time by solving hCaptcha every time I want to display the listing's contact information. @durch can you help? Also CC'ing @armfazh.

**Comment by BTCAlchemist** [comment] 2021-07-08 00:25
Issue is still outstanding. @durch & @armfazh is someone available to look into it?

**Comment by ppopth** [comment] 2021-07-12 12:06
@BTCAlchemist We have updated the new version 2.0.9 and it solved the issue on hCaptcha tokens. It now works on the challenge in the home page of hCaptcha https://www.hcaptcha.com/ , but it doesn't work on https://www.tokyobitcoiner.com/hcaptcha

I'm thinking that maybe tokyobitcoiner has some specific configuration?

Can you please try it out in other websites as well and inform us if there is still a problem?

**Comment by BTCAlchemist** [comment] 2021-07-13 02:00
@ppopth Thank you for your reply. I tried it on Craigslist but am still required to solve the captcha, even though I have 4 hCaptcha passes. This has been happening for me on Craigslist for several weeks. Here is the link and a screenshot. Please let me know if you need any additional information. Any ideas on how to fix this? https://sfbay.craigslist.org/nby/apa/d/sausalito-adu-studio-on-historic/7339936650.html

![image](https://user-images.githubusercontent.com/56145569/125378289-5434ea00-e343-11eb-83e3-1029d39b6523.png)

**Comment by ppopth** [comment] 2021-07-13 14:33
@BTCAlchemist It doesn't work at all or it doesn't work sometimes? I tried that website already and it works totally fine for me. Can you clear all passes first and try again?

**Comment by BTCAlchemist** [comment] 2021-07-13 22:36
@ppopth I have Privacy Pass set to work when I click the extension. I cleared the passes and earned new ones, clicked to activate the extension, but craigslist.org still required hCaptcha completion.

My next step was to change the extension setting to enable Privacy Pass on all websites. At that point, it worked on []. This didn't previously work, so I'm glad to see the issue fixed with this setting in the current version. Sounds like the error occurs when the setting "Allow this extension to read and change all your data on websites you visit" is set to "On click" or to "On specific sites" (snip below). Is this a known issue? Maybe it's incompatible if the web page is a subdomain but hCaptcha might require root domain permission?

![image](https://user-images.githubusercontent.com/56145569/125533882-69637362-c3db-4075-b0ca-1e2654ef1abe.png)

**Comment by ppopth** [comment] 2021-07-14 07:30
@BTCAlchemist I think this is known. The extension should work only on the "On all sites" option because the extension doesn't read/hook the requests only on the domain you visit, it also needs to read/hook the requests for other domains from the page as well (for example, hcaptcha.com request to fetch/resolve the captcha)

**Comment by ppopth** [comment] 2021-07-14 07:30
I think it's okay now to close this issue, right?

**Comment by BTCAlchemist** [comment] 2021-07-15 05:40
Thank you, @ppopth. Would it be possible to add a note about this in the extension description, so folks won't have trouble around extension permissions going forward? Sounds ready to close the issue.

**Comment by BTCAlchemist** [comment] 2021-09-20 23:31
@ppopth Privacy Pass extension works on https://www.hcaptcha.com/ but is not working on a Cloudflare Captcha page at https://help.coinbase.com/en/pro.html. I have passes and have the extension enabled on all sites. Is compatibility with Cloudflare a known issue?

![image](https://user-images.githubusercontent.com/56145569/134089787-9c5ca9ad-78aa-4c4f-9bcc-a3e1c61d1a27.png)

**Comment by BTCAlchemist** [comment] 2021-10-02 20:13
Got this issue again when trying to access https://wallet.uphold.com. I lose one hCaptcha pass from Privacy Pass, but I am still required to complete the captcha challenge. @ppopth Can you reproduce this on your end?
![Screen Shot 2021-10-02 at 1 10 24 PM](https://user-images.githubusercontent.com/56145569/135730609-88f896f2-f995-4bd3-bda2-0a888e22973b.png)
/

**Comment by BTCAlchemist** [comment] 2021-10-08 20:22
Still not working. This time on https://www.g2.com/compare/foxit-pdf-editor-vs-pdfelement
![image](https://user-images.githubusercontent.com/56145569/136620522-8332c329-42c2-475d-8657-8dec22bc3b0e.png)

**Comment by usafety** [comment] 2022-03-11 01:00
You hast test your Plugin with Brave Browser?

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------

**Comment by usafety** [comment] 2022-03-11 01:06
yes its based on Google Chrome but much better for privacy.

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------

**Comment by migueldemoura** [comment] 2022-05-19 00:00
I'm unable to reproduce this with Brave `[Version 1.38.115 Chromium: 101.0.4951.64 (Official Build) (x86_64)]`.

Also note that individual websites can choose to disable support for PrivacyPass, preventing you from using one of the tokens on it.

**Comment by BTCAlchemist** [comment] 2022-05-20 13:27
@migueldemoura I just tried this on macOS Brave browser but could not even get hCaptcha passes from https://www.hcaptcha.com/privacy-pass. The extension version is 3.0.2.

**Comment by migueldemoura** [comment] 2022-05-20 13:33
@BTCAlchemist see https://github.com/privacypass/challenge-bypass-extension/issues/310#issuecomment-1125484037:

```
support for hCaptcha is on standby until further notice.
```

Are you able to get tokens for Cloudflare?

**Comment by BTCAlchemist** [comment] 2022-05-20 17:31
Yes, I was able to earn 30 Cloudflare tokens. However, I never had to use them before. If hCaptcha support could be fixed, that would make a big difference.

> Are you able to get tokens for Cloudflare?

**Comment by migueldemoura** [comment] 2022-05-20 18:10
That's great! Closing this issue, we'll track hCaptcha support in https://github.com/privacypass/challenge-bypass-extension/issues/310.

**Closed by migueldemoura** 2022-05-20 18:10 UTC
