### ISSUE TITLE
[BUG] Tickets don't update, Cloudflare's not working

### ISSUE THREAD

**Issue by nsde** [privacypass/challenge-bypass-extension#318] opened 2022-05-06 23:16 UTC
![image](https://user-images.githubusercontent.com/67185896/167226840-1dbb0da9-257b-429a-901e-24867760dded.png)
## Whenever I click on "get more passes" for "Cloudflare", I get redirected:
![image](https://user-images.githubusercontent.com/67185896/167226864-87b8506a-8557-474b-a94a-c77840f0359f.png)
## After answering all questions (correctly) and clicking "Verify"...
![image](https://user-images.githubusercontent.com/67185896/167226977-e4724d66-e944-45fd-8dc7-cad9689c3e93.png)
## ... just nothing happens:
![image](https://user-images.githubusercontent.com/67185896/167226906-7dafc661-79c1-4146-8e39-2e0d25c97c33.png)
## And after a bit of time, I get asked again:
![image](https://user-images.githubusercontent.com/67185896/167226929-921fdb40-d154-4583-9636-0a93fcf5f3f6.png)
## But my tickets aren't updated:
![image](https://user-images.githubusercontent.com/67185896/167226960-da9a08b6-c36f-46e3-9e13-bd4f259d1472.png)

**Comment by migueldemoura** [comment] 2022-05-06 23:39
Duplicate of https://github.com/privacypass/challenge-bypass-extension/issues/317?

**Comment by nsde** [comment] 2022-05-06 23:51
> Duplicate of #317?
I also use Firefox. But Idk for sure since there is not much info/screenshots provided.

**Comment by iugmali** [comment] 2022-05-07 02:36
I had happened to me also... I use google chrome latest version.

**Comment by armfazh** [comment] 2022-05-07 03:28
ACK, problem was identified and CF is working on the solution. 
Not an issue on the side of extension.

**Comment by ilf** [comment] 2022-05-09 10:50
> ACK, problem was identified and CF is working on the solution. Not an issue on the side of extension.

Thanks for your work. And thanks for CF to fix this.

But I can't understand how [Cloudflare officially supports Privacy Pass](https://blog.cloudflare.com/cloudflare-supports-privacy-pass/) but breaks it without warning for days at end again and again.

**Comment by dreamboxgate** [comment] 2022-05-10 15:45
get more passes not working on chrome 101.0.4951.54

**Comment by hubbingits** [comment] 2022-05-11 16:59
I'm having the same issue. 

I'm using Chrome Version 101.0.4951.64 (Official Build) (64-bit)

**Comment by armfazh** [comment] 2022-05-12 19:37
CF experienced some issues [last week](https://www.cloudflarestatus.com/incidents/f6cv9cxtfdj2). Solved now.

**Closed by armfazh** 2022-05-12 19:37 UTC
