### ISSUE TITLE
not works in firefox

### ISSUE THREAD

**Issue by ilyapashuk** [privacypass/challenge-bypass-extension#177] opened 2020-06-02 12:26 UTC
**Describe the bug**
does not up a counter when I pass captcha

**To Reproduce**
1. Go to extension window and click cloud flare or hcaptcha
2. you can be redirected to your github.io page or to captcha page
3. try to solve the captcha
4. sea that token counter does not up

**System (please complete the following information):**
 - OS: windows7
all tokens
firefox
76
2.06
from firefox store

**Additional context**

**Comment by alxdavids** [comment] 2020-06-02 14:17
Thanks for the report.

I've tried in Firefox (v76.0.1) and it worked okay. I also updated to v77 right now and it also worked fine. Would you be able to try updating and seeing if the problem endures?

**Comment by ilyapashuk** [comment] 2020-06-02 18:57
performed one other test, works for cloud flare, not for HCaptcha, but all tokens removed immediately after exit.

**Comment by ilyapashuk** [comment] 2020-06-02 19:21
now updated, the same. all resets on exit

**Comment by alxdavids** [comment] 2020-06-03 09:33
Do you delete cookies / material from localStorage when the browser exits? We store tokens in the browser local storage.

**Comment by alxdavids** [comment] 2020-08-06 09:10
Is this still a problem with hCaptcha? If there is no update, I'll close this out.

**Comment by migueldemoura** [comment] 2022-05-24 13:57
I'm unable to reproduce this, and 2 years have passed since the initial report. Please feel free to reopen if the issue persists!

**Closed by migueldemoura** 2022-05-24 13:57 UTC
