### ISSUE TITLE
Browser becomes unresponsive while generating passes

### ISSUE THREAD

**Issue by da2x** [privacypass/challenge-bypass-extension#69] opened 2019-02-05 14:02 UTC
Browser: Tor Browser 8.0.5 (based on Mozilla Firefox 60.5.0esr) (64-bit) macOS

1. Install extension
2. Visit https://captcha.website/
3. Suffer through the reCAPTCHA

Actual:
The browser becomes unresponsive for over a minute. I can’t change tab or interact with it. macOS shows it’s spinning beach-ball of death cursor animation. The process takes so much time that by the time the browser becomes usable again, that reCAPTCHA complains that the token has expired. At the end I’ve generated 30 new tokens, though.

Expected:
The browser to remain intractable.

**Comment by alxdavids** [comment] 2019-02-06 16:11
Does this happen every time you try to get tokens? Does it only happen for you on the Tor browser also, or across different browsers (e.g. actual Firefox)?

**Comment by da2x** [comment] 2019-02-06 19:23
This happens every time I get tokens with Tor Browser 8.0.5 (based on Mozilla Firefox 60.5.0esr) (64-bit) on macOS, Windows 10, and Fedora Linux.

As for testing in regular Firefox: I can’t. The “Get More Passes” button just loads the project website.

**Comment by da2x** [comment] 2019-02-07 18:22
I’ve installed it from [AMO](https://addons.mozilla.org/firefox/addon/privacy-pass/).

**Comment by alxdavids** [comment] 2019-02-07 18:30
I've just downloaded and tried this and I don't seem to be able to reproduce the same issue, do you have any other extensions installed?

**Comment by da2x** [comment] 2019-02-09 19:12
After some digging I found the missing step:

1. Click the Tor option button (Onion icon): Security Settings
2. Switch the security slider to Safer (middle option)
3. Visit https://captcha.website/
4. Suffer through the reCAPTCHA

The [documentation for this option](https://tb-manual.torproject.org/en-US/security-slider.html) says:

>  all JavaScript performance optimizations are disabled

I'd still say it's unexpected that the browser will become unresponsive, however. Can the work be shifted to a service worker to run off the main thread?

**Comment by alxdavids** [comment] 2019-02-11 09:36
Thanks for the update, it's good to be aware of such performance issues. It's possible that we could do this, but it's probably not something that we're going to get around to immediately. We are open to external contributions so I'll leave this issue up to track it going forward.

**Comment by sesam** [comment] 2019-02-13 11:23
Maybe a setInterval to update a message "still generating (## seconds)..." (like gmail) so anything longer than 2 seconds shows what's happening. Useful independently of extracting into a service worker.

**Comment by sesam** [comment] 2019-05-07 12:04
Finally I've been able to get this to generate passes. Also on a new MBP the 30 passes take quite some time. How about, at least during testing, we decrease from 30 to 10? Or make an option. Also, if it is possible to manually trigger getting passes somehow, then the default could be to add a very small amount, and when you trigger it manually you could only then have the extension build a bigger amount of tokens.

**Comment by chpio** [comment] 2021-02-25 10:45
Would doing all the crypto stuff in wasm reduce the problem? A wasm impl should be more efficient than doing it in unoptimized js. Does the tor browser (with enabled JS, but disabled JS optimizations) support wasm?

**Comment by thibmeu** [comment] 2023-12-21 11:38
The extension and the protocol have changed quite a lot since this ticket has been opened. As we are working to upgrade the extension to support the latest IETF draft, we are centralising updates in https://github.com/privacypass/challenge-bypass-extension/issues/400. I'm closing this ticket as duplicate.

**Closed by thibmeu** 2023-12-21 11:38 UTC
Labels: enhancement, tor
