### ISSUE TITLE
captcha.website does not detect Privacy Pass 3.0

### ISSUE THREAD

**Issue by ilf** [privacypass/challenge-bypass-extension#293] opened 2022-02-03 10:04 UTC
I installed Privacy Pass 3.0 (on Tor Browser 11.0.4).
Visiting https://captcha.website/ shows no captcha challenge, but tells me to install the (already-installed) plugin.

![captcha website](https://user-images.githubusercontent.com/160771/152321368-bf00a88b-5638-46d5-b951-6ccb803a96d0.png)

**Comment by rolltidehero** [comment] 2022-02-03 10:11
Also same thing on Edge but now sure if it works on Edge or now

**Comment by ppopth** [comment] 2022-02-03 11:24
Possibly you access the website and get the cf_clearance cookie before installing the extension. The extension is supposed to remove any existing cookie for the website, but it's not implemented yet.

Could you please remove the cookies of captcha.website? and then try using the extension again. The extension should work fine afterwards.

**Comment by ppopth** [comment] 2022-02-03 11:27
I just noticed that you are using Tor Browser. We are still having an issue with Tor Browser in #277 I'm not sure it's related and I haven't tried to debug yet. Let's try removing the cookies first and see how it goes.

**Comment by ilf** [comment] 2022-02-03 11:34
> Could you please remove the cookies of captcha.website?

This is not it. I tried by closing TBB, clearing all cookies, restarting TBB and opening captcha.website without any cookies whatsoever.

**Comment by ilf** [comment] 2022-02-03 11:35
> We are still having an issue with Tor Browser in #277 I'm not sure it's related and I haven't tried to debug yet.

I filed #277 and that's a different bug. This one here happens way before, I don't even get to the point of #277 any more.

**Comment by alerque** [comment] 2022-02-04 10:13
This might be a duplicate of #291.

**Comment by mendelsphotography** [comment] 2022-02-06 02:17
I think this is a copy of #291 it was updated to 3.0.1 which seemed to fix it so try now Updating and see I suggest @ilf

**Comment by alerque** [comment] 2022-02-06 07:04
As of 3.0.1 this is working for me on CloudFlair and the captcha.website site, but still not for hCaptcha. That might be a different issue, so this perhaps can be closed.

**Comment by mendelsphotography** [comment] 2022-02-06 08:13
Yep me to I open a new issue about the hCaptacha #294

**Comment by ilf** [comment] 2022-02-06 12:58
I am trying to test this with 3.0.1. Unfortunately, I can't get past the Cloudflare Captcha wall:

![captcha](https://user-images.githubusercontent.com/160771/152681858-54516110-0ecd-48ed-9094-55584e8fe9fe.png)

The wonders of using Cloudflare Captchas to get around Coudflare Captchas…

**Comment by alerque** [comment] 2022-02-06 13:16
@ilf Same problem here, just since last night. 3.0.1 had started to work for me, now not only does it not work but on multiple devices I'm not even getting the captcha's to load. As shown in your screen shot it just gets stuck at checking browser...

**Comment by ilf** [comment] 2022-02-07 09:57
Same (new) issue in Chromium 98.0.4758.80 without Tor:

![captcha](https://user-images.githubusercontent.com/160771/152765885-027f83af-8630-40a2-b069-803e66a75858.png)

**Comment by ppopth** [comment] 2022-02-07 11:18
captcha.website is a special web page which is used only for issuing the tokens. You will always see the captcha page in captcha.website, so this is expected.

**Comment by ilf** [comment] 2022-02-07 11:47
ppopth: I don't understand.

First, Cloudflare issues a Captcha BEFORE I can visit captcha.website. This fails now.

Second, captcha.website shows a Captcha to get tokens. This was not displayed in the original bug report.

**Comment by ppopth** [comment] 2022-02-07 12:21
>I am trying to test this with 3.0.1. Unfortunately, I can't get past the Cloudflare Captcha wall:
I replied to this sentence. Getting the captcha page in captcha.website is an expected behavior.

**Comment by ppopth** [comment] 2022-02-07 12:26
Oh sorry, I didn't notice that the issue is on the "Please stand by,..." message. I just tried again now and it didn't get stuck on that message.

Can you try again (not in Tor Browser) and see if it still get stuck on that message?

**Comment by ilf** [comment] 2022-02-07 12:46
> Can you try again (not in Tor Browser) and see if it still get stuck on that message?

Just tried again, in Chromium 98.0.4758.80 without Tor, still stuck on "Please stand by, while we are checking your browser..."

**Comment by alerque** [comment] 2022-02-07 19:24
@ppopth On Saturday (after updating to 3.0.1) I was able to visit captcha.website and it showed the captcha and each time I filled it out I got 30 tokens. Starting on Sunday and continuing till just now, it never even shows a captcha it is just stuck on "please stand by, while we are checking your browser" (comma mistake theirs). It never gets past that to an actual captcha.

**Comment by Mathew-D** [comment] 2022-02-07 23:19
I get the same please wait message and when I go to inspect I get the following:
![image](https://user-images.githubusercontent.com/44036272/152888483-25f2a83f-414f-4055-bef7-f908e5445d88.png)

**Comment by alerque** [comment] 2022-02-08 08:23
Cloudflairs links to this plugin from their captcha guard page. You would think if it was official enough to endorse with a link they might do just a *little* regression testing so that it isn't broken 364 days out of 365.

**Comment by Deyrap355** [comment] 2022-02-08 10:55
What do I need to do to stop all the errors

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ppopth** [comment] 2022-02-08 11:06
@Mathew-D is that from the tab developer tool or the extension developer tool?

**Comment by Deyrap355** [comment] 2022-02-08 11:18
Extension developer tool

**Comment by ilf** [comment] 2022-02-08 11:32
Still not working here, in two browsers. https://captcha.website/ still doesn't display, only "Please stand by, while we are checking your browser..."

**Comment by ppopth** [comment] 2022-02-09 05:08
Could anyone give me the HAR file from the tab developer tool please? I cannot reproduce it yet.

**Comment by ilf** [comment] 2022-02-09 08:08
I feel uneasy publishing the entire HAR file, but here's the error log: [captcha.website.log](https://github.com/privacypass/challenge-bypass-extension/files/8030675/captcha.website.log)

```
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
captcha.website/:1          GET https://captcha.website/ 403
api.js?render=explicit&recaptchacompat=off&onload=_cf_chl_hload:2 recaptchacompat disabled
favicon.ico:1          GET https://captcha.website/favicon.ico 403
v1?ray=6dab9657ce372669:1 [[[ERROR]]]: Message: Uncaught SyntaxError: Invalid or unexpected token - URL: https://captcha.website/ - Line: 3 - Column: 1 - Error object: {} undefined
VM40:3 Uncaught SyntaxError: Invalid or unexpected token
    at new Function (<anonymous>)
    at XMLHttpRequest.E.<computed> (v1?ray=6dab9657ce372669:1:10975)
E.<computed> @ v1?ray=6dab9657ce372669:1
XMLHttpRequest.send (async)
d.<computed> @ v1?ray=6dab9657ce372669:1
setTimeout (async)
(anonymous) @ v1?ray=6dab9657ce372669:1
z.<computed> @ v1?ray=6dab9657ce372669:1
u @ v1?ray=6dab9657ce372669:1
d._cf_chl_enter @ v1?ray=6dab9657ce372669:1
(anonymous) @ v1?ray=6dab9657ce372669:1
(anonymous) @ v1?ray=6dab9657ce372669:1
setTimeout (async)
A.<computed> @ v1?ray=6dab9657ce372669:1
x @ v1?ray=6dab9657ce372669:1
(anonymous) @ v1?ray=6dab9657ce372669:1
(anonymous) @ v1?ray=6dab9657ce372669:1
```

**Comment by ilf** [comment] 2022-02-19 15:37
Still true with 3.0.1:

![pp](https://user-images.githubusercontent.com/160771/154807723-7e2bc451-4ccf-469b-9d3e-93c1aca848a7.png)

**Comment by migueldemoura** [comment] 2022-05-20 13:35
@ilf are you still able to reproduce the issue?

**Comment by ilf** [comment] 2022-05-24 19:38
@migueldemoura Now https://captcha.website/ shows me a challenge even though I have 30 tokens:

![captcha website](https://user-images.githubusercontent.com/160771/170118366-02322944-3bbd-4f63-a05a-2020471047e3.png)

**Comment by alerque** [comment] 2022-05-24 20:01
@ilf That's what it is supposed to do! That website's only purpose is to just keep showing you captchas and (if it is working) racking up tokens in the process.

**Comment by armfazh** [comment] 2022-11-14 21:19
Closing as it seems to be a confusion with the purpose of captcha.website page.

_The sole purpose of captcha.website is to gain Cloudflare tokens after solving a captcha._

@ilf please open a new ticket if you see new issues.

**Closed by armfazh** 2022-11-14 21:19 UTC
Labels: tor

**Comment by ilf** [comment] 2022-11-18 11:57
I have a feeling everyone got carried away by the discussion in the 30+ comments. But I do not see how or where the issue from the very first post was solved: https://captcha.website/ said "please install the plugin" - even tough it is already installed.
