### ISSUE TITLE
Doesn't generate any token

### ISSUE THREAD

**Issue by malnvenshorn** [privacypass/challenge-bypass-extension#25] opened 2018-02-22 10:23 UTC
This plugin is a nice idea but it doesn't seem to work at all (at least not in chrome). I can solve one cloudflare captcha after another but I never pass them nor does the plugin generate any tokens/passes (it shows constantly 0).

**Comment by malnvenshorn** [comment] 2018-02-23 09:18
Yes I downloaded the extension from the chrome store. Additionally I'm using `HTTPS Everywhere` and `uBlock Origin`. The latter one was disabled for testing.

I tried this with different websites, e.g. https://captcha.website, https://medium.com, https://getbootstrap.com and of course https://www.cloudflare.com

**Comment by malnvenshorn** [comment] 2018-02-23 09:56
I also took a look with the developer tools, but sadly there is no debug output in the console.

**Comment by malnvenshorn** [comment] 2018-02-23 14:30
Did some more digging. The reason why privacy pass doesn't generate tokes is that `manualChallenge` and `captchaResp` are always `false`.

https://github.com/privacypass/challenge-bypass-extension/blob/a058f67c7739da4fb88be3d94b1423dd2cc50b50/scripts/background.js#L268-L275

**Comment by alxdavids** [comment] 2018-02-24 08:45
I've just downloaded the extension from the chrome store and it works fine for me, also we're still seeing thousands of active users globally so maybe this is an isolated case. This would suggest that those variables are not always false, what gives you that impression?

What version of Chrome are you running? Do you have javascript enabled?

You could also try pulling the code from this repo directly and running that in the browser (there are some changes in the repo that are yet to be pushed to an official store version).

**Comment by malnvenshorn** [comment] 2018-02-24 13:25
I've set a break point after the if-clause and I noticed that it never reaches that point in the program. So I've set another break point before the if-clause and inspected those variables. They were always `false` which explains why no tokens are generated.

JavaScript is enabled and Chrome version is 64.0.3282.170.

**Comment by inmamind** [comment] 2018-03-07 00:58
Hi, I've tried to use this extention, however it is not working for me, both on Chrome Version 64.0.3282.186 (Official Build) (64-bit) and Firefox Quantum 58.0.2.

I downloaded the extention from the chrome store and Firefox Add-ons. It is not working on two different Ubuntu laptops and one Window laptop. Javascript is enabled.

Also, I can find any Captcha test on https://captcha.website/. 

It would be appreciated, if you could provide some advice for me to use this extention.

**Comment by briceb8e** [comment] 2018-03-17 22:11
Same thing happening here. Thanks.

**Comment by alxdavids** [comment] 2018-03-18 08:19
Okay thanks, I'm going to look into this in the coming days.

**Comment by Razva** [comment] 2018-05-30 16:28
Doesn't works at the moment. When clicking "Get Passes" I'm redirected to https://captcha.website/ but without any option to "add passes".

**Comment by sianhulo** [comment] 2018-07-14 14:21
I, too, can't see any captchas in their site (Firefox 63 / linux)

**Comment by alxdavids** [comment] 2018-08-22 19:48
I've tried without any luck to recreate the problems that are being witnessed here.

Just to check, when you click "Get More Passes" you should be able to see a Cloudflare CAPTCHA page (i.e. https://captcha.website). Solving the CAPTCHA should grant you tokens. I will make this clearer in the readme.

**Comment by lahma69** [comment] 2018-09-12 03:34
I am also experiencing this same behavior. I am using Chrome stable on Windows 10, and when I click the extension's button in the toolbar and click 'Get More Passes', it opens a new tab on 'https://captcha.website/'. I then proceed to solve the captcha, and once I get a green checkmark, indicating I solved the captcha successfully, the extension still states that I have 0 passes. Oddly enough, I just tried this for a 4th time while writing this post (so I could describe the process more clearly), and this time, it finally gave me 30 passes. I followed the same exact process for the 1st 3 attempts, and despite solving the captchas successfully, the extension still said I had 0 passes available. There is clearly something very inconsistent going on under the hood. I'm busy doing about 10 different things simultaneously at the moment, but if it would be helpful to provide any logs or debug output (if I can reproduce the behavior), let me know, and I will attempt to provide whatever might be helpful.

**Comment by l-g** [comment] 2018-09-28 23:08
I don't even get any captchas to solve. What gives?

**Comment by alxdavids** [comment] 2018-11-05 22:03
It seems like the recurring issue is that people are not seeing a captcha when they navigate to https://captcha.website. This may be a regional issue?

The original issue seems different but may be linked to the null point errors (#50).

**Comment by myfreeweb** [comment] 2018-12-12 14:43
I don't get any captchas when using a proxy. Captchas are showing up after adding `captcha.website` to the "No Proxy For" list in Firefox.

**Comment by ronjouch** [comment] 2018-12-19 22:53
No captcha here either when browsing to https://captcha.website/ with Firefox Nightly 66.0a1 (2018-12-19) (64-bit) on Linux with a fresh new profile (zero state, no configuration, no addons except PrivacyPass, no VPN, no proxy). Request emitted from Montréal, QC, Canada. GIF:

![no-captcha-here-either](https://user-images.githubusercontent.com/522085/50252935-9f1e3900-03b6-11e9-9bc7-091bd75d634f.gif)

**Comment by alxdavids** [comment] 2019-01-07 00:01
> In my case, I got 300 or so tokens, then it stopped gathering new ones.

This is exactly as it is meant to work.

> No captcha here either when browsing to https://captcha.website/ with Firefox Nightly 66.0a1 (2018-12-19) (64-bit) on Linux with a fresh new profile (zero state, no configuration, no addons except PrivacyPass, no VPN, no proxy). Request emitted from Montréal, QC, Canada.

Okay, good to know, thanks.

**Comment by nukeop** [comment] 2019-03-28 10:49
My case is very similar to what @ronjouch reported.

**Comment by kjsparks** [comment] 2019-03-28 21:27
It was working fine.  Then I updated to FireFox 66.0.1, now it doesn't generate passes any more.  I've tried dozens of times, no luck.  I can't even get passed the captcha on any web site now.  It gives the green check, but doesn't refresh, and if I refresh, I get to do the captcha again.  Over and over...

**Comment by kjsparks** [comment] 2019-03-28 23:08
Okay, I found out why -- the WebRTC protection plug in interferes with PrivacyPass somehow if you have WebRTC leak protection ON.  Not sure how, but I found if I disabled that plug-in, it worked.  Then I tried with it enabled but with leak protection OFF (bad), and then PrivacyPass did get passes.

Can you make PrivacyPass work with WebRTC ON?

**Comment by alxdavids** [comment] 2019-03-29 10:32
> Okay, I found out why -- the WebRTC protection plug in interferes with PrivacyPass somehow if you have WebRTC leak protection ON. Not sure how, but I found if I disabled that plug-in, it worked. Then I tried with it enabled but with leak protection OFF (bad), and then PrivacyPass did get passes.
> 
> Can you make PrivacyPass work with WebRTC ON?

Maybe create a separate issue for this, and I'll see if I can look into it.

**Comment by kjsparks** [comment] 2019-03-29 16:29
> > Okay, I found out why -- the WebRTC protection plug in interferes with PrivacyPass somehow if you have WebRTC leak protection ON. Not sure how, but I found if I disabled that plug-in, it worked. Then I tried with it enabled but with leak protection OFF (bad), and then PrivacyPass did get passes.
> > Can you make PrivacyPass work with WebRTC ON?
> 
> Maybe create a separate issue for this, and I'll see if I can look into it.

My sincere apologies.  This appears to have been a red herring.  While no passes could be generated yesterday, and my investigation led to WebRTC being off to get passes at the end of day yesterday, my attempts to repro today have resulted in getting passes with WebRTC on or OFF today.  I'm not sure why no passes could be generated yesterday.  I'll keep an eye on it.

**Comment by tleydxdy** [comment] 2019-07-18 21:10
no pass for me too, one of my core gets fully loaded for a while and nothing happens after that.

**Comment by monterrr** [comment] 2019-10-30 21:54
For me on firefox 70 it always shows 0 passes but the extension seems to be working because when I go to solve a captcha it doesn't require work from me.

**Comment by kjsparks** [comment] 2019-11-04 22:13
> For me on firefox 70 it always shows 0 passes but the extension seems to be working because when I go to solve a captcha it doesn't require work from me.

Same here immediately upon FF 70 update.

**Comment by alxdavids** [comment] 2019-11-28 14:06
These problems may have been fixed in the > 2.0 release? I've never been able to reproduce the problems in this thread (not even sure if they're all related). I'm going to close this issue but if we get more reports then happy to reopen.

**Closed by alxdavids** 2019-11-28 14:06 UTC
Labels: investigate

**Comment by tleydxdy** [comment] 2019-11-28 18:04
I was able to get passes after I dropped Enhanced Tracking Protection in firefox from strict to standard.
