### ISSUE TITLE
Doesn't work on Firefox, at all

### ISSUE THREAD

**Issue by GunGunGun** [privacypass/challenge-bypass-extension#362] opened 2022-12-01 01:55 UTC
Before reporting a new bug, verify if your request is already being tracked by another issue: https://github.com/privacypass/challenge-bypass-extension/issues.

---

If you believe that this is a new bug, please proceed to create an issue. The issue will be investigated after you have filled in the following information.

**Describe the bug**
I install newest PrivacyPass on a fresh new newest Firefox 107 install and profile (so don't tell me to create a new profile and reinstall Firefox), click PrivacyPass button and Get more passes, do captcha/bot checks and after more than 20 times I still got 0 passes, please check this addon on Firefox.

**How to reproduce**
1. Go to website.captcha
2. Click on captcha/bot checks
3. Scroll down to PrivacyPass icon
Got zero passes.

**Expected behavior**
A description of what is expected to happen.
Should get 30 passes because I tried on Chrome 5 times, got 150 passes. https://i.imgur.com/49cXoh9.png

**System (please complete the following information):**
 - OS: [e.g. iOS/Windows] Windows 7
 - Cloudflare tokens or hCaptcha tokens? Both
 - Browser [e.g. chrome, firefox] Firefox 107
 - Browser Version [e.g. 79, 80, ] Firefox 107
 - Privacy Pass Version [e.g. 2.0.4, 2.0.5 ] 3.0.4, the lastest verison: https://i.imgur.com/DtyufLo.png

**Additional context**
Nothing more because I've already explained more than enough. Just some screenshots:
Firefox version: https://i.imgur.com/FfABVdn.png
Result: https://i.imgur.com/NUXKcaG.png
Chrome (worked): https://i.imgur.com/49cXoh9.png

**Comment by armfazh** [comment] 2022-12-01 04:56
Thanks for reporting, I can reproduce the issue.

**Comment by ericpa06** [comment] 2022-12-01 14:03
I'm experiencing the same issue. I'm using **Firefox Developer 108.b8** and it is the same issue: even after resolving the captcha, the page simply doesn't give you credits.

**Comment by GunGunGun** [comment] 2022-12-01 15:18
> I'm experiencing the same issue. I'm using **Firefox Developer 108.b8** and it is the same issue: even after resolving the captcha, the page simply doesn't give you credits.

So far I tested PrivacyPass 3.0.3 to 3.0.4 on Firefox 104-107, none of them worked. And though my sample size was good enough so I stopped.

**Comment by armfazh** [comment] 2022-12-01 17:28
There is an identified issue with CF tokens, solution will come.
OTOH, no issues to get hcaptcha tokens.

**Comment by hucario** [comment] 2022-12-02 17:19
While the problem _does_ cause you to be unable to solve **any** cloudflare captcha, you can disable the extension and things start working again. AFAIK the extension blocks the page from working normally, fails to make it work itself, and does not detect this and allow the page to work normally on failure

**Comment by ericpa06** [comment] 2022-12-02 18:12
Thank you very much hucario. Disabling the extension solved my issue. I thought the problem was something affecting Cloudflare interaction with Firefox in general – with or without the Privacy by Pass extension. I just realized know that it hadn't occurred to try to disable the extension 😂 Again, thank you very much :)

**Comment by 32bitx64bit** [comment] 2022-12-06 23:16
Im having a similar issue only that the cloudflare part gets stuck on 'processing' works fine when i remove PrivacyPass tho

**Comment by erincerys** [comment] 2022-12-11 13:06
God, this shit still doesn't work? Wasn't it a year ago that it was broken for completely different reasons? Fix one thing, a month later it just breaks again, and before the PR is even accepted for the first thing. Is this project just perpetually unusable?

**Comment by armfazh** [comment] 2022-12-13 20:13
Fixes to the service has been deployed by Cloudflare. It works now.

**Closed by armfazh** 2022-12-13 20:13 UTC
Labels: cf
