### ISSUE TITLE
Passes randomly (but consistently) disappearing

### ISSUE THREAD

**Issue by ahydronous** [privacypass/challenge-bypass-extension#158] opened 2020-04-13 18:24 UTC
Hello,

My passes are constantly disappearing. This most often happens with a reboot and semi-frequently happens with a system sleep or a browser quit. I'll come back to a black extension icon, and if I go get more passes via 'get more passes' I'll have a red '!!!' before I finish the CAPTCHA and get my new passes

**Comment by alxdavids** [comment] 2020-04-16 08:38
Which browser are you using?

**Comment by ahydronous** [comment] 2020-04-22 23:35
Firefox 75.0 on macOS Catalina 10.15.3.

My list of extensions is:
(one of these seems a more likely trouble causer)
- Canvasblocker
- Cookiebro (set to erase all cookies from non-whitelisted URLs at startup + every 60 mins, as well as erase Localstorage and IndexDB on browser startup, although I rarely if ever restart my browser)
- Decentraleyes
- I don't care about cookies (ignore cookiewalls and set sites to the minimum necessary needed cookies to function)
- Privacy Pass
- Smart Referer (returns source url as referer)
- uBlock Origin (runs in default deny mode for 3rd party frames and scripts)

(these seem less likely)
- 1Password X
- Automatic Spell Checking Language selection
- Behind the overlay revival
- h246ify
- Saka Key
- Violentmonkey (only runs a dark mode YouTube userscript)

**Comment by alxdavids** [comment] 2020-04-24 10:12
> Cookiebro (set to erase all cookies from non-whitelisted URLs at startup + every 60 mins, as well as erase Localstorage and IndexDB on browser startup, although I rarely if ever restart my browser)

Privacy Pass tokens are stored in local storage, so this is likely to be the cause. Does this still happen with this extension disabled?

**Comment by ahydronous** [comment] 2020-04-25 19:39
Disabling seems to have done the trick, thanks!

**Comment by NoahCardoza** [comment] 2020-05-06 03:58
I am having a similar problem and I have tried installing the extension on a completely new profile of Chrome and it still doesn't work correctly. If I try to get hCaptcha tokens nothing happens after solving one. If I try to get CF tokens it will say I have 30, but if I clear the cookies and reload the page to get a captcha again it will still say 30 until I click the captcha and it displays "!!!"

Any idea? Already tried using Firefox as well.

**Comment by alxdavids** [comment] 2020-05-06 08:26
> I am having a similar problem and I have tried installing the extension on a completely new profile of Chrome and it still doesn't work correctly. If I try to get hCaptcha tokens nothing happens after solving one. If I try to get CF tokens it will say I have 30, but if I clear the cookies and reload the page to get a captcha again it will still say 30 until I click the captcha and it displays "!!!"
> 
> Any idea? Already tried using Firefox as well.

I guess this means that when you clear cookies it is also clearing localStorage where the tokens are stored. This doesn't trigger the extension popup, and so the next time it is triggered, the extension will show that you have 0 tokens.

**Comment by alxdavids** [comment] 2020-05-07 11:35
Since the original issue here has been fixed, I'm going to close this.

**Closed by alxdavids** 2020-05-07 11:35 UTC
Labels: investigate
